import type { Metadata } from "next";
import { Inter } from "next/font/google";
import SessionWrapper from "@/components/SessionWrapper";
import { CssBaseline } from "@mui/material";
import ThemeWrapper from "@/components/ThemeWrapper";
import Layout from "@/components/Layout/Layout";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "DataSoft",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <SessionWrapper>
      <html lang="en">
        <body className={inter.className}>
          <ThemeWrapper>
            <CssBaseline />
            <Layout>{children}</Layout>
          </ThemeWrapper>
        </body>
      </html>
    </SessionWrapper>
  );
}
